System.config({
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.2.1",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.2.5",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.5",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
    "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge@0.5.1",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.3",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1",
    "css": "github:systemjs/plugin-css@0.1.21",
    "fetch": "github:github/fetch@1.0.0",
    "font-awesome": "npm:font-awesome@4.6.1",
    "jquery": "npm:jquery@2.2.3",
    "text": "github:systemjs/plugin-text@0.0.7",
    "github:Dogfalo/materialize@0.97.6": {
      "css": "github:systemjs/plugin-css@0.1.21",
      "jquery": "npm:jquery@2.2.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.2.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-binding@1.0.0-beta.1.3.6": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.5",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.3",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-framework@1.0.0-beta.1.2.5": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.6",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.2.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.2.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-loader@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.2.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-materialize-bridge@0.5.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.6",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.3",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7",
      "materialize": "github:Dogfalo/materialize@0.97.6"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-router@1.0.0-beta.1.2.3": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.2.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.6",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.2.6": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.6",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.2.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.3",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating@1.0.0-beta.1.2.7": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.6",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1"
    },
    "npm:font-awesome@4.6.1": {
      "css": "github:systemjs/plugin-css@0.1.21"
    }
  },
  bundles: {
    "app-build.js": [
      "app.html!github:systemjs/plugin-text@0.0.7.js",
      "app.js",
      "blur-image.js",
      "child-router.html!github:systemjs/plugin-text@0.0.7.js",
      "child-router.js",
      "main.js",
      "nav-bar.html!github:systemjs/plugin-text@0.0.7.js",
      "users.html!github:systemjs/plugin-text@0.0.7.js",
      "users.js",
      "welcome.html!github:systemjs/plugin-text@0.0.7.js",
      "welcome.js"
    ],
    "aurelia.js": [
      "github:Dogfalo/materialize@0.97.6.js",
      "github:dogfalo/materialize@0.97.6/css/materialize.css!github:systemjs/plugin-css@0.1.21.js",
      "github:dogfalo/materialize@0.97.6/js/materialize.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.1.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.1/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.6.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.6/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.5.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.5/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.5.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.5/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.1.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.1/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.2.1.js",
      "npm:aurelia-history@1.0.0-beta.1.2.1/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.2.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.2/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.1.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.1/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.1.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.1/aurelia-logging.js",
      "npm:aurelia-materialize-bridge@0.5.1.js",
      "npm:aurelia-materialize-bridge@0.5.1/badge/badge.js",
      "npm:aurelia-materialize-bridge@0.5.1/box/box.js",
      "npm:aurelia-materialize-bridge@0.5.1/breadcrumbs/breadcrumbs.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/breadcrumbs/breadcrumbs.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/breadcrumbs/breadcrumbs.js",
      "npm:aurelia-materialize-bridge@0.5.1/breadcrumbs/instructionFilter.js",
      "npm:aurelia-materialize-bridge@0.5.1/button/button.js",
      "npm:aurelia-materialize-bridge@0.5.1/card/card.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/card/card.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/card/card.js",
      "npm:aurelia-materialize-bridge@0.5.1/carousel/carousel-item.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/carousel/carousel-item.js",
      "npm:aurelia-materialize-bridge@0.5.1/carousel/carousel.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/carousel/carousel.js",
      "npm:aurelia-materialize-bridge@0.5.1/char-counter/char-counter.js",
      "npm:aurelia-materialize-bridge@0.5.1/checkbox/checkbox.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/checkbox/checkbox.js",
      "npm:aurelia-materialize-bridge@0.5.1/chip/chip.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/chip/chip.js",
      "npm:aurelia-materialize-bridge@0.5.1/click-counter.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/click-counter.js",
      "npm:aurelia-materialize-bridge@0.5.1/collapsible/collapsible.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-header.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-header.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-header.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-item.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-item.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection-item.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/collection.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/md-collection-selector.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/md-collection-selector.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/collection/md-collection-selector.js",
      "npm:aurelia-materialize-bridge@0.5.1/colors/colorValueConverters.js",
      "npm:aurelia-materialize-bridge@0.5.1/colors/md-colors.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/common/attributeManager.js",
      "npm:aurelia-materialize-bridge@0.5.1/common/attributes.js",
      "npm:aurelia-materialize-bridge@0.5.1/common/constants.js",
      "npm:aurelia-materialize-bridge@0.5.1/common/events.js",
      "npm:aurelia-materialize-bridge@0.5.1/config-builder.js",
      "npm:aurelia-materialize-bridge@0.5.1/datepicker/datepicker.js",
      "npm:aurelia-materialize-bridge@0.5.1/dropdown/dropdown-element.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/dropdown/dropdown-element.js",
      "npm:aurelia-materialize-bridge@0.5.1/dropdown/dropdown.js",
      "npm:aurelia-materialize-bridge@0.5.1/fab/fab.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/fab/fab.js",
      "npm:aurelia-materialize-bridge@0.5.1/file/file.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/file/file.js",
      "npm:aurelia-materialize-bridge@0.5.1/footer/footer.js",
      "npm:aurelia-materialize-bridge@0.5.1/index.js",
      "npm:aurelia-materialize-bridge@0.5.1/input/input-prefix.js",
      "npm:aurelia-materialize-bridge@0.5.1/input/input-update-service.js",
      "npm:aurelia-materialize-bridge@0.5.1/input/input.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/input/input.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/input/input.js",
      "npm:aurelia-materialize-bridge@0.5.1/modal/modal-trigger.js",
      "npm:aurelia-materialize-bridge@0.5.1/navbar/navbar.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/navbar/navbar.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/navbar/navbar.js",
      "npm:aurelia-materialize-bridge@0.5.1/pagination/pagination.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/pagination/pagination.js",
      "npm:aurelia-materialize-bridge@0.5.1/parallax/parallax.js",
      "npm:aurelia-materialize-bridge@0.5.1/progress/progress.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/progress/progress.js",
      "npm:aurelia-materialize-bridge@0.5.1/pushpin/pushpin.js",
      "npm:aurelia-materialize-bridge@0.5.1/radio/radio.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/radio/radio.js",
      "npm:aurelia-materialize-bridge@0.5.1/range/range.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/range/range.js",
      "npm:aurelia-materialize-bridge@0.5.1/scrollfire/scrollfire-patch.js",
      "npm:aurelia-materialize-bridge@0.5.1/scrollfire/scrollfire-target.js",
      "npm:aurelia-materialize-bridge@0.5.1/scrollfire/scrollfire.js",
      "npm:aurelia-materialize-bridge@0.5.1/scrollspy/scrollspy.js",
      "npm:aurelia-materialize-bridge@0.5.1/select/select.js",
      "npm:aurelia-materialize-bridge@0.5.1/sidenav/sidenav-collapse.js",
      "npm:aurelia-materialize-bridge@0.5.1/sidenav/sidenav.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/sidenav/sidenav.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/sidenav/sidenav.js",
      "npm:aurelia-materialize-bridge@0.5.1/slider/slider.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/slider/slider.js",
      "npm:aurelia-materialize-bridge@0.5.1/switch/switch.css!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/switch/switch.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-materialize-bridge@0.5.1/switch/switch.js",
      "npm:aurelia-materialize-bridge@0.5.1/tabs/tabs.js",
      "npm:aurelia-materialize-bridge@0.5.1/toast/toastService.js",
      "npm:aurelia-materialize-bridge@0.5.1/tooltip/tooltip.js",
      "npm:aurelia-materialize-bridge@0.5.1/transitions/fadein-image.js",
      "npm:aurelia-materialize-bridge@0.5.1/transitions/staggered-list.js",
      "npm:aurelia-materialize-bridge@0.5.1/waves/waves.js",
      "npm:aurelia-materialize-bridge@0.5.1/well/md-well.html!github:systemjs/plugin-text@0.0.7.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.1.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.1/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.1.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.1/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.2.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.2/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.2.2.js",
      "npm:aurelia-path@1.0.0-beta.1.2.2/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.4.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.4/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.2.3.js",
      "npm:aurelia-router@1.0.0-beta.1.2.3/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.1.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.1/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.4.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.4/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/hide.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.7.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js",
      "npm:jquery@2.2.3.js",
      "npm:jquery@2.2.3/dist/jquery.js"
    ]
  },
  depCache: {
    "blur-image.js": [
      "aurelia-framework"
    ],
    "users.js": [
      "aurelia-framework",
      "aurelia-fetch-client",
      "fetch"
    ]
  }
});